name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev pkg-config
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true
    
    - name: Install Soroban CLI
      run: cargo install --locked soroban-cli --version 23.1.3
    
    - name: Build optimized contracts
      run: |
        # Build all contracts with optimization
        for contract in contracts/*/; do
          if [ -f "$contract/Cargo.toml" ]; then
            echo "Building optimized contract in $contract"
            cd "$contract"
            soroban contract build --out-dir ../../target/wasm32-unknown-unknown/release/
            cd ../..
          fi
        done
        
        # Build contracts in course subdirectory
        for contract in contracts/course/*/; do
          if [ -f "$contract/Cargo.toml" ]; then
            echo "Building optimized contract in $contract"
            cd "$contract"
            soroban contract build --out-dir ../../../target/wasm32-unknown-unknown/release/
            cd ../../..
          fi
        done
    
    - name: Create release artifacts
      run: |
        mkdir -p release-artifacts
        cp target/wasm32-unknown-unknown/release/*.wasm release-artifacts/ 2>/dev/null || true
        ls -la release-artifacts/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-artifacts/*.wasm
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
